name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and test Flutter app using Docker
        run: |
          cd frontend
          docker build -t odyssey-frontend .
          docker run odyssey-frontend

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and test Spring Boot app using Docker
        run: |
          cd backend
          docker build -t odyssey-backend .
          docker run odyssey-backend ./mvnw test